### ISSUE TITLE
forEach not defined in JsvHttpParamSerializer.js

### ISSUE THREAD

**Issue by ghost** [czesiu/angular-jsv#1]
Angular.js 1.4.3
Angular-JSV 1.0.1

During a resolve call, the passed in query parameters in the format of [{Key:key,Value:value}] were causing the forEach on line 68 to throw as undefined. Changing to angular.forEach corrects the error and makes the external call successfully.

![angular-jsv_1](https://cloud.githubusercontent.com/assets/510005/13989060/ba5b6944-f0dc-11e5-8981-21ccd2046f6e.PNG)

**Comment by czesiu** [comment]
I merged pull request and added new release. Thanks for support.
